version: 2

linux_image: &linux_image
  docker:
    - image: circleci/golang:1.15
  working_directory: /go/src/github.com/codeclimate/test-reporter
  setup_remote_docker:
    docker_layer_caching: true

setup_macos_env: &setup_macos_env


jobs:
  test_linux:
    <<: *linux_image
    steps:
      - checkout
      - run: make test

  release_head_linux:
    <<: *linux_image
    steps:
      - checkout
      - run: sudo apt-get install awscli
      - run: make build-linux-all VERSION=head
      - run: make publish-head

  test_macos:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout
      - run:
          command: sh .circleci/install_go.sh 
      - run:
          name: Run tests
          command: |
            cd $GOPATH/src/github.com/codeclimate/test-reporter
            make test

  release_head_macos:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout
      - run: pip install awscli
      - run:
          command: sh .circleci/install_go.sh
      - run:
          name: Build
          command: |
            cd $GOPATH/src/github.com/codeclimate/test-reporter
            make build-darwin VERSION=head
      - run:
          name: Publish
          command: |
            cd $GOPATH/src/github.com/codeclimate/test-reporter
            make publish-head

workflows:
  version: 2
  build_deploy:
    jobs:
      - test_linux
      - test_macos
      - release_linux:
          requires:
            - test_linux
            - test_macos
          filters:
            branches:
              only:
                - master
      - release_macos:
          requires:
            - test_linux
            - test_macos
          filters:
            branches:
              only:
                - master

notify:
  webhooks:
    - url: https://cc-slack-proxy.herokuapp.com/circle
